name: Deploy Latest

on:
## TODO!!!! MAKE THIS CHRON
  workflow_run:
    workflows: ["Smoke Tests and ECR Upload"]
    types:
      - completed

jobs:
  pull_from_ecr:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install boto3
      
      - name: Pull Latest and Run New Code
        env:
          INSTANCE_ID: ${{ secrets.INSTANCE_ID }}          
        run: python scripts/ec2/use_latest.py
      
