name: Deploy Latest

on:
### TODO!!!! MAKE THIS CHRON
  workflow_run:
    workflows: ["Smoke Tests and ECR Upload"]
    types:
      - completed

jobs:
  Pull_from_ECR:
    uses: ubuntu-24.04
    
    
  
