name: Deploy Latest

on:
### TODO!!!! MAKE THIS CHRON
  workflow_run:
    workflows: ["Smoke Tests and ECR Upload"]
    types:
      - completed

jobs:
  Pull_from_ECR:
    runs-on: ubuntu-24.04
    
    steps:
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
      name: Install Dependencies
      run: pip install boto3 paramiko
      
      name: Pull Latest Image Into EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
