name: Deploy Infrastructure

on:
  repository_dispatch:
    types: [deploy]
jobs:
  receive-event:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v4
      - name: Log Received Event
        run: |
          echo "Received dispatch event with ref: ${{ github.event.client_payload.ref }}"
      - name: Checkout Application Code
        uses: actions/checkout@v4
        with:
          repository: drshooby/Sharenet-Vue-Spa
          ref: ${{ github.event.client_payload.ref }}
          path: app
          token: ${{ secrets.PAT }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create Temporary EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd scripts
          pip install boto3 paramiko
          python ec2/temporary/deploy_tmp_ec2.py
